//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// dict_analyze_res.rc

#define IDD_MAIN                            100

#define IDS_APPNAME                         100
#define IDS_SMALL                           105
#define IDS_LARGE                           106
#define IDS_EXTDIFFERENT                    107
#define IDS_READINGSTARTED                  108
#define IDS_READINGDONE                     109
#define IDS_ANALYZESTART                    110
#define IDS_ANALYZEDONE                     111
#define IDS_READINGFAILED                   112
#define IDS_ANALYZEFAILED                   113

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
